[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:postgresql-k8s-3
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  test-storage-postgresql-k8s/0 [idle] waiting: agent initialising
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  test-storage-postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  test-storage-postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  test-storage-postgresql-k8s/0 [idle] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.7    unsupported  02:11:24Z

App                          Version  Status  Scale  Charm           Channel  Rev  Address         Exposed  Message
postgresql-k8s               14.18    active      3  postgresql-k8s             2  10.152.183.247  no       
test-storage-postgresql-k8s  14.18    active      1  postgresql-k8s             3  10.152.183.129  no       Primary

Unit                            Workload  Agent  Address       Ports  Message
postgresql-k8s/0                active    idle   10.1.224.220         
postgresql-k8s/1                active    idle   10.1.224.222         
postgresql-k8s/2*               active    idle   10.1.224.221         Primary
test-storage-postgresql-k8s/0*  active    idle   10.1.224.224         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-postgresql-k8s-0: 01:33:04 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:33:41 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 01:37:19 ERROR unit.postgresql-k8s/2.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-postgresql-k8s-0: 01:45:59 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-k8s-1: 01:46:02 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-k8s-1: 01:49:48 ERROR unit.postgresql-k8s/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-postgresql-k8s-0: 02:00:51 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 02:01:44 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 02:01:54 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 02:02:02 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 02:04:13 ERROR unit.postgresql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3407, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-k8s-2/relation-get', '-r', '3', '-', 'postgresql-k8s', '--app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 2520, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 563, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 405, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 411, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 732, in wrap_init
    original_init(self, framework, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 261, in __init__
    self._observer.start_authorisation_rules_observer()
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/authorisation_rules_observer.py", line 59, in start_authorisation_rules_observer
    or not self._charm.is_cluster_initialised
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 422, in is_cluster_initialised
    return "cluster_initialised" in self.app_peer_data
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 883, in __contains__
    return key in self._data
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 876, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 1846, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3486, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3409, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied (unauthorized access)

controller-0: 02:04:24 ERROR juju.worker.caasapplicationprovisioner.runner exited "postgresql-k8s": finding filesystem info for postgresql-k8s-pgdata-1bc005e8: unable to get persistent volume claim: k8s: persistentvolumeclaims "postgresql-k8s-pgdata-1bc005e8-postgresql-k8s-2" not found
unit-postgresql-k8s-1: 02:06:49 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-0: 02:06:57 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 02:06:57 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...