[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app/0 [idle] active: received database credentials of the first database
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  another-database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/data-integrator-78
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  another-data-integrator/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [executing] blocked: Please relate the data-integrator with the desired product
  another-data-integrator/0 [executing] blocked: Please specify either topic, index, or database name
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [executing] active: 
  database/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.6.2    unsupported  01:49:29Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    344  10.152.183.80   no       received database credentials of the first database
another-data-integrator           blocked      1  data-integrator      latest/stable   78  10.152.183.18   no       Please relate the data-integrator with the desired product
another-database         14.15    active       3  postgresql-k8s                        0  10.152.183.100  no       
data-integrator                   blocked      1  data-integrator      latest/stable   78  10.152.183.87   no       Please relate the data-integrator with the desired product
database                 14.15    active       3  postgresql-k8s                        1  10.152.183.236  no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    344  10.152.183.163  no       received database credentials of the first database

Unit                        Workload  Agent  Address       Ports  Message
another-application/0*      active    idle   10.1.183.150         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.183.154         Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.183.147         Primary
another-database/1          active    idle   10.1.183.148         
another-database/2          active    idle   10.1.183.149         
data-integrator/0*          blocked   idle   10.1.183.153         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.183.144         Primary
database/1                  active    idle   10.1.183.152         
database/2                  active    idle   10.1.183.151         
postgresql-test-app/0*      active    idle   10.1.183.136         received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.183.137         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-database-2: 01:32:22 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-1: 01:32:22 ERROR unit.database/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-1: 01:32:33 ERROR unit.database/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:32:34 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-another-database-2: 01:33:27 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:33:34 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-0: 01:39:29 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 01:39:29 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 01:39:39 ERROR unit.database/0.juju-log Kubernetes service get failed: services "database" not found
unit-database-0: 01:39:39 ERROR unit.database/0.juju-log Kubernetes service patch failed: services "database" not found
unit-database-0: 01:48:23 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 01:48:23 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 254, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 01:48:25 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 01:48:25 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 92, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 254, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles

[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...