[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] waiting: Awaiting restart operation
  postgresql-k8s/2 [executing] active: Primary
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/2 [executing] active: Primary
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/1 [executing] active: 
  postgresql-k8s/2 [idle] waiting: Awaiting restart operation
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] waiting: Awaiting restart operation
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] waiting: Awaiting restart operation
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/1 [idle] waiting: Awaiting restart operation
  postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.7    unsupported  01:47:13Z

App                       Version                         Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
mattermost                .../mattermost:v8.1.3-20.04...  active      2  mattermost-k8s            latest/stable   27  10.152.183.151  no       
postgresql-k8s            14.18                           active      3  postgresql-k8s                             0  10.152.183.192  no       
self-signed-certificates                                  active      1  self-signed-certificates  latest/stable  264  10.152.183.184  no       

Unit                         Workload  Agent  Address    Ports     Message
mattermost/0*                active    idle   10.1.0.17  8065/TCP  
mattermost/1                 active    idle   10.1.0.16  8065/TCP  
postgresql-k8s/0*            active    idle   10.1.0.12            
postgresql-k8s/1             active    idle   10.1.0.14            
postgresql-k8s/2             active    idle   10.1.0.13            Primary
self-signed-certificates/0*  active    idle   10.1.0.11            

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-postgresql-k8s-2: 01:34:37 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:34:37 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:34:45 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 01:34:45 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:43:53 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "3d2c6d22-7b74-413d-8d8e-d6733ab97bba:r#3#self-signed-certificates": settings 3d2c6d22-7b74-413d-8d8e-d6733ab97bba:r#3#self-signed-certificates not found (not found)
unit-postgresql-k8s-0: 01:43:58 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "3d2c6d22-7b74-413d-8d8e-d6733ab97bba:r#3#self-signed-certificates": settings 3d2c6d22-7b74-413d-8d8e-d6733ab97bba:r#3#self-signed-certificates not found (not found)
unit-postgresql-k8s-1: 01:44:29 ERROR unit.postgresql-k8s/1.juju-log failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 437, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 184, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.testing.svc.cluster.local" (10.152.183.63), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/charm.py", line 797, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 466, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError() from e
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...