{"uid":"709209a51b031fd8","name":"test_restore_on_new_cluster","fullName":"tests.integration.test_backups_gcp#test_restore_on_new_cluster","historyId":"7016e18fce65bb14bbb75a176490233f","time":{"start":1742953829315,"stop":1742954220410,"duration":391095},"description":"Test that is possible to restore a backup to another PostgreSQL cluster.","descriptionHtml":"<p>Test that is possible to restore a backup to another PostgreSQL cluster.</p>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fe63c7ce9f0 state=finished raised AssertionError>]","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/tests/integration/test_backups_gcp.py\", line 143, in test_restore_on_new_cluster\n    assert restore_status, \"restore hasn't succeeded\"\nAssertionError: restore hasn't succeeded\nassert None\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/test_backups_gcp.py\", line 130, in test_restore_on_new_cluster\n    for attempt in Retrying(\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 443, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 376, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 419, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7fe63c7ce9f0 state=finished raised AssertionError>]","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1742952610397,"stop":1742952610397,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"charm","time":{"start":1742952610397,"stop":1742952610397,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1742952610397,"stop":1742952610397,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1742952610398,"stop":1742952610605,"duration":207},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"gcp_cloud_configs","time":{"start":1742952610606,"stop":1742952610608,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1742953829314,"stop":1742953829314,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Test that is possible to restore a backup to another PostgreSQL cluster.","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fe63c7ce9f0 state=finished raised AssertionError>]","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/tests/integration/test_backups_gcp.py\", line 143, in test_restore_on_new_cluster\n    assert restore_status, \"restore hasn't succeeded\"\nAssertionError: restore hasn't succeeded\nassert None\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/test_backups_gcp.py\", line 130, in test_restore_on_new_cluster\n    for attempt in Retrying(\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 443, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 376, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 419, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7fe63c7ce9f0 state=finished raised AssertionError>]","steps":[],"attachments":[{"uid":"b787a37789d05a24","name":"log","source":"b787a37789d05a24.txt","type":"text/plain","size":2062}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1742954220415,"stop":1742954220415,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"gcp_cloud_configs::finalizer","time":{"start":1742954423250,"stop":1742954433246,"duration":9996},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1742954433247,"stop":1742954433637,"duration":390},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1742954433638,"stop":1742954433638,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1742954433638,"stop":1742954433638,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1742954433638,"stop":1742954433638,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_backups_gcp"},{"name":"host","value":"fv-az2035-585"},{"name":"thread","value":"19113-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_backups_gcp"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"a2487164e7ea95f3","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":22,"skipped":0,"passed":18,"unknown":0,"total":40},"items":[{"uid":"b8573357a875484e","reportUrl":"../3796//#testresult/b8573357a875484e","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f0f27da2b40 state=finished raised AssertionError>]","time":{"start":1742868089105,"stop":1742868545565,"duration":456460}},{"uid":"9cac8092dd61e92e","reportUrl":"../3787//#testresult/9cac8092dd61e92e","status":"passed","time":{"start":1742780838249,"stop":1742781079391,"duration":241142}},{"uid":"e543c50b5c48c45","reportUrl":"../3786//#testresult/e543c50b5c48c45","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f9243d40aa0 state=finished raised AssertionError>]","time":{"start":1742694531180,"stop":1742694888723,"duration":357543}},{"uid":"7044778d316fc358","reportUrl":"../3785//#testresult/7044778d316fc358","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fc2041e39e0 state=finished raised AssertionError>]","time":{"start":1742608279571,"stop":1742608721838,"duration":442267}},{"uid":"11daf4e39b905e89","reportUrl":"../3776//#testresult/11daf4e39b905e89","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fb97edb2720 state=finished raised AssertionError>]","time":{"start":1742521895711,"stop":1742522337283,"duration":441572}},{"uid":"4d52ffd0b97753ae","reportUrl":"../3767//#testresult/4d52ffd0b97753ae","status":"passed","time":{"start":1742435387157,"stop":1742435730744,"duration":343587}},{"uid":"e0d6627bb4806e4a","reportUrl":"../3755//#testresult/e0d6627bb4806e4a","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fd24bf42630 state=finished raised AssertionError>]","time":{"start":1742349018669,"stop":1742349423092,"duration":404423}},{"uid":"3497013dcb0c9e2d","reportUrl":"../3743//#testresult/3497013dcb0c9e2d","status":"passed","time":{"start":1742262804919,"stop":1742263123216,"duration":318297}},{"uid":"6957beeaa944f424","reportUrl":"../3742//#testresult/6957beeaa944f424","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f40bd5c7320 state=finished raised AssertionError>]","time":{"start":1742003412439,"stop":1742003810364,"duration":397925}},{"uid":"cbfa76a9f46b4b7e","reportUrl":"../3739//#testresult/cbfa76a9f46b4b7e","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7efca9ff9460 state=finished raised AssertionError>]","time":{"start":1741917112759,"stop":1741917538332,"duration":425573}},{"uid":"849133706a8de6e3","reportUrl":"../3725//#testresult/849133706a8de6e3","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fb115bda3f0 state=finished raised AssertionError>]","time":{"start":1741830619325,"stop":1741831040089,"duration":420764}},{"uid":"eec5e29b4a6026bb","reportUrl":"../3724//#testresult/eec5e29b4a6026bb","status":"passed","time":{"start":1741744129672,"stop":1741744393386,"duration":263714}},{"uid":"92f5492f06f0bb8b","reportUrl":"../3718//#testresult/92f5492f06f0bb8b","status":"passed","time":{"start":1741657785828,"stop":1741658166243,"duration":380415}},{"uid":"30e9dff09a1c637b","reportUrl":"../3715//#testresult/30e9dff09a1c637b","status":"passed","time":{"start":1741571378707,"stop":1741571701781,"duration":323074}},{"uid":"bb2106bf4aaa235c","reportUrl":"../3714//#testresult/bb2106bf4aaa235c","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f714dfd1520 state=finished raised AssertionError>]","time":{"start":1741485052511,"stop":1741485500462,"duration":447951}},{"uid":"6fbe4b9537c4e32","reportUrl":"../3712//#testresult/6fbe4b9537c4e32","status":"passed","time":{"start":1741398577636,"stop":1741398893705,"duration":316069}},{"uid":"64a68f86137fa4f4","reportUrl":"../3696//#testresult/64a68f86137fa4f4","status":"passed","time":{"start":1741312237639,"stop":1741312560450,"duration":322811}},{"uid":"b67dd723b25ae4b5","reportUrl":"../3680//#testresult/b67dd723b25ae4b5","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f0ab4187410 state=finished raised AssertionError>]","time":{"start":1741225913673,"stop":1741226326027,"duration":412354}},{"uid":"79806a439c7a6761","reportUrl":"../3676//#testresult/79806a439c7a6761","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fd11438b590 state=finished raised AssertionError>]","time":{"start":1741139469220,"stop":1741139879149,"duration":409929}},{"uid":"c24715fae013fe5a","reportUrl":"../3669//#testresult/c24715fae013fe5a","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7fb0eccf2630 state=finished raised AssertionError>]","time":{"start":1741053962555,"stop":1741054370475,"duration":407920}}]},"tags":["asyncio"]},"source":"709209a51b031fd8.json","parameterValues":[]}