[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:78 scaling database to zero units
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:82 scaling database to three units
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 0)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: installing charm software
  postgresql-k8s/1 [idle] waiting: awaiting for cluster to start
  postgresql-k8s/2 [executing] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/2 [executing] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [idle] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] unknown: 
  postgresql-k8s/1 [idle] active: Primary (degraded)
  postgresql-k8s/2 [idle] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s/1 [executing] active: Primary (degraded)
  postgresql-k8s/2 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: 
  postgresql-k8s/1 [idle] active: Primary (degraded)
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for member to start
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: Primary
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:86 waiting for the database service to start in all units
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:92 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:242 Initial writes {'testing.postgresql-k8s-0': 1001, 'testing.postgresql-k8s-1': 1001, 'testing.postgresql-k8s-2': 1001}
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:248 Retry writes {'testing.postgresql-k8s-0': 1005, 'testing.postgresql-k8s-1': 1005, 'testing.postgresql-k8s-2': 1006}
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:96 checking whether all units are part of the same cluster
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:105 checking whether no writes to the database were missed after stopping the writes
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.114:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.10   unsupported  01:50:02Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
postgresql-k8s       14.19    active      3  postgresql-k8s                      0  10.152.183.232  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  406  10.152.183.244  no       received database credentials of the first database

Unit                    Workload  Agent  Address      Ports  Message
postgresql-k8s/0        active    idle   10.1.242.79         
postgresql-k8s/1*       active    idle   10.1.242.81         Primary
postgresql-k8s/2        active    idle   10.1.242.80         
postgresql-test-app/0*  active    idle   10.1.242.75         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-postgresql-k8s-0: 01:39:09 ERROR unit.postgresql-k8s/0.juju-log failed to patch k8s Endpoints postgresql-k8s-primary
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/endpoints/postgresql-k8s-primary?force=true&fieldManager=postgresql-k8s'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/charm.py", line 1462, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on endpoints "postgresql-k8s-primary": the object has been modified; please apply your changes to the latest version and try again
unit-postgresql-k8s-0: 01:39:09 ERROR unit.postgresql-k8s/0.juju-log failed to patch k8s Endpoints postgresql-k8s-replicas
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/endpoints/postgresql-k8s-replicas?force=true&fieldManager=postgresql-k8s'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/charm.py", line 1462, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on endpoints "postgresql-k8s-replicas": the object has been modified; please apply your changes to the latest version and try again
unit-postgresql-k8s-0: 01:39:09 ERROR unit.postgresql-k8s/0.juju-log failed to patch k8s Service patroni-postgresql-k8s-config
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/services/patroni-postgresql-k8s-config?force=true&fieldManager=postgresql-k8s'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/charm.py", line 1462, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on services "patroni-postgresql-k8s-config": the object has been modified; please apply your changes to the latest version and try again

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...