[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app/0 [idle] active: received database credentials of the first database
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  another-database/0 [idle] active: 
  another-database/1 [idle] active: Primary
  another-database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/data-integrator-78
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  another-data-integrator/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [executing] blocked: Please relate the data-integrator with the desired product
  another-data-integrator/0 [executing] blocked: Please specify either topic, index, or database name
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:936 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  02:06:09Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    373  10.152.183.105  no       received database credentials of the first database
another-data-integrator           blocked      1  data-integrator      latest/stable   78  10.152.183.213  no       Please relate the data-integrator with the desired product
another-database         14.17    active       3  postgresql-k8s                        1  10.152.183.195  no       
data-integrator                   blocked      1  data-integrator      latest/stable   78  10.152.183.248  no       Please relate the data-integrator with the desired product
database                 14.17    active       3  postgresql-k8s                        0  10.152.183.52   no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    373  10.152.183.127  no       received database credentials of the first database

Unit                        Workload  Agent  Address       Ports  Message
another-application/0*      active    idle   10.1.134.150         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.134.154         Please relate the data-integrator with the desired product
another-database/0          active    idle   10.1.134.143         
another-database/1*         active    idle   10.1.134.144         Primary
another-database/2          active    idle   10.1.134.145         
data-integrator/0*          blocked   idle   10.1.134.153         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.134.147         Primary
database/1                  active    idle   10.1.134.151         
database/2                  active    idle   10.1.134.152         
postgresql-test-app/0       active    idle   10.1.134.136         received database credentials of the first database
postgresql-test-app/1*      active    idle   10.1.134.137         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:942 Juju error logs:

unit-another-database-2: 01:44:00 ERROR unit.another-database/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3320, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-another-database-2/secret-get', '--label', 'database-peers.another-database.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-another-database-2/charm/src/charm.py", line 2395, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 558, in main
    manager.run()
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 543, in run
    self._emit()
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 530, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 906, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 996, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-another-database-2/charm/src/charm.py", line 982, in _on_postgresql_pebble_ready
    self.unit.set_workload_version(self._patroni.rock_postgresql_version)
  File "/var/lib/juju/agents/unit-another-database-2/charm/src/charm.py", line 1654, in _patroni
    self.get_secret(APP_SCOPE, USER_PASSWORD_KEY),
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-another-database-2/charm/src/charm.py", line 364, in get_secret
    return self.peer_relation_data(scope).get_secret(peers.id, secret_key)
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 521, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2044, in get_secret
    and full_field not in self.current_secret_fields
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2001, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2332, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1124, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 508, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2319, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 812, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-another-database-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 642, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 308, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3692, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-another-database-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3322, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-another-database-2: 01:44:00 ERROR juju.worker.uniter.operation hook "postgresql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-another-database-2: 01:44:00 ERROR juju.worker.uniter pebble poll failed for container "postgresql": failed to send pebble-ready event: hook failed
unit-database-1: 01:46:18 ERROR unit.database/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:46:18 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-1: 01:46:47 ERROR unit.database/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-another-database-2: 01:47:52 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-test-app-1: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-application-0: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-0: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-0: 01:54:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-2: 01:59:24 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:59:34 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-0: 02:04:56 ERROR unit.database/0.juju-log database:20: Invalid extra user roles: test
unit-database-0: 02:04:56 ERROR unit.database/0.juju-log database:20: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 105, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 300, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles
unit-database-0: 02:05:00 ERROR unit.database/0.juju-log database:21: Invalid extra user roles: test
unit-database-0: 02:05:00 ERROR unit.database/0.juju-log database:21: invalid role(s) for extra user roles
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-0/charm/src/relations/postgresql_provider.py", line 105, in _on_database_requested
    self.charm.postgresql.create_user(user, password, extra_user_roles=extra_user_roles)
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-database-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 300, in create_user
    raise PostgreSQLCreateUserError(INVALID_EXTRA_USER_ROLE_BLOCKING_MESSAGE)
charms.postgresql_k8s.v0.postgresql.PostgreSQLCreateUserError: invalid role(s) for extra user roles

[32mINFO    [0m pytest_operator.plugin:plugin.py:1024 Forgetting model main...