[32mINFO    [0m integration.test_backups_ceph:test_backups_ceph.py:48 Setting up TLS certificates
[32mINFO    [0m integration.test_backups_ceph:test_backups_ceph.py:113 Setting up microceph
[32mINFO    [0m integration.test_backups_ceph:test_backups_ceph.py:142 Creating microceph bucket
[32mINFO    [0m integration.test_backups_ceph:test_backups_ceph.py:160 Set up microceph
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:806 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/s3-integrator-145
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/self-signed-certificates-264
[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:postgresql-k8s-0
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [allocating] waiting: installing agent
  postgresql-k8s-ceph/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [allocating] waiting: agent initialising
  postgresql-k8s-ceph/1 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s-ceph/1 [executing] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s-ceph/1 [executing] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] maintenance: Executing restart operation
  postgresql-k8s-ceph/1 [idle] unknown: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [executing] active: Primary (degraded)
  postgresql-k8s-ceph/1 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.helpers:helpers.py:861 configuring S3 integrator for ceph
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [executing] active: Primary
  postgresql-k8s-ceph/1 [executing] active: 
  s3-integrator/0 [executing] blocked: Missing parameters: ['access-key', 'secret-key']
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [executing] active: Primary
  postgresql-k8s-ceph/1 [executing] active: 
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:882 creating a table in the database
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:893 creating a backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [executing] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:902 listing the available backups
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:911 creating a second table in the database
[32mINFO    [0m integration.helpers:helpers.py:918 creating a backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:929 listing the available backups
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] active: Primary
  postgresql-k8s-ceph/1 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:938 creating a second table in the database
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph (waiting for exactly 1 units, current : 2)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] active: Primary
[32mINFO    [0m integration.helpers:helpers.py:954 restoring the backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] maintenance: restoring backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] maintenance: restoring backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] active: Primary
[32mINFO    [0m integration.helpers:helpers.py:967 checking that the backup was correctly restored
[32mINFO    [0m integration.helpers:helpers.py:999 restoring the backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-ceph/0 [idle] maintenance: restoring backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] maintenance: restoring backup
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s-ceph/0 [idle] active: Primary
[32mINFO    [0m integration.helpers:helpers.py:1012 checking that the backup was correctly restored
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.11   unsupported  01:42:03Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
postgresql-k8s-ceph       14.19    active      1  postgresql-k8s                             0  10.152.183.121  no       
s3-integrator                      active      1  s3-integrator             latest/stable  145  10.152.183.67   no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  264  10.152.183.103  no       

Unit                         Workload  Agent  Address       Ports  Message
postgresql-k8s-ceph/0*       active    idle   10.1.113.140         Primary
s3-integrator/0*             active    idle   10.1.113.136         
self-signed-certificates/0*  active    idle   10.1.113.137         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-postgresql-k8s-ceph-1: 01:32:24 ERROR unit.postgresql-k8s-ceph/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3637, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-k8s-ceph-1/secret-get', '--label', 'database-peers.postgresql-k8s-ceph.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/src/charm.py", line 2545, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 486, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 421, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 465, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 924, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 1030, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1153, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/src/charm.py", line 991, in _on_postgresql_pebble_ready
    self.unit.set_workload_version(self._patroni.rock_postgresql_version)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/src/charm.py", line 1634, in _patroni
    self.get_secret(APP_SCOPE, PATRONI_PASSWORD_KEY),
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1153, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/src/charm.py", line 387, in get_secret
    if result := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key):
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1732, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1721, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 656, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2613, in _fetch_my_specific_relation_data
    self.component, self.local_secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2235, in local_secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2259, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2600, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1452, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 628, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2587, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 934, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 764, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 325, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 4023, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-ceph-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3639, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-postgresql-k8s-ceph-1: 01:32:24 ERROR juju.worker.uniter.operation hook "postgresql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-ceph-1: 01:32:24 ERROR juju.worker.uniter pebble poll failed for container "postgresql": failed to send pebble-ready event: hook failed

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...