[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app/0 [idle] active: received database credentials of the first database
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  database/0 [executing] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  another-database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/jammy/data-integrator-78
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  another-data-integrator/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  data-integrator/0 [executing] blocked: Please relate the data-integrator with the desired product
  another-data-integrator/0 [executing] blocked: Please specify either topic, index, or database name
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [idle] active: 
  database/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] blocked: invalid role(s) for extra user roles
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/0 [idle] active: Primary
  database/1 [executing] active: 
  database/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  database/1 [idle] active: 
  database/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.7    unsupported  02:01:50Z

App                      Version  Status   Scale  Charm                Channel        Rev  Address         Exposed  Message
another-application               active       1  postgresql-test-app  latest/edge    388  10.152.183.207  no       received database credentials of the first database
another-data-integrator           blocked      1  data-integrator      latest/stable   78  10.152.183.165  no       Please relate the data-integrator with the desired product
another-database         14.18    active       3  postgresql-k8s                        0  10.152.183.158  no       
data-integrator                   blocked      1  data-integrator      latest/stable   78  10.152.183.105  no       Please relate the data-integrator with the desired product
database                 14.18    active       3  postgresql-k8s                        1  10.152.183.23   no       
postgresql-test-app               active       2  postgresql-test-app  latest/edge    388  10.152.183.57   no       received database credentials of the first database

Unit                        Workload  Agent  Address      Ports  Message
another-application/0*      active    idle   10.1.129.22         received database credentials of the first database
another-data-integrator/0*  blocked   idle   10.1.129.26         Please relate the data-integrator with the desired product
another-database/0*         active    idle   10.1.129.19         Primary
another-database/1          active    idle   10.1.129.21         
another-database/2          active    idle   10.1.129.20         
data-integrator/0*          blocked   idle   10.1.129.25         Please relate the data-integrator with the desired product
database/0*                 active    idle   10.1.129.15         Primary
database/1                  active    idle   10.1.129.24         
database/2                  active    idle   10.1.129.23         
postgresql-test-app/0*      active    idle   10.1.129.8          received database credentials of the first database
postgresql-test-app/1       active    idle   10.1.129.9          received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-another-database-2: 01:34:29 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:35:01 ERROR unit.database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-1: 01:35:01 ERROR unit.database/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-another-database-2: 01:35:51 ERROR unit.another-database/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-database-2: 01:45:02 ERROR unit.database/2.juju-log failed to patch k8s Endpoints patroni-database-config
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/endpoints/patroni-database-config?force=true&fieldManager=database'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/src/charm.py", line 1467, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on endpoints "patroni-database-config": the object has been modified; please apply your changes to the latest version and try again
unit-database-2: 01:45:02 ERROR unit.database/2.juju-log failed to patch k8s Endpoints patroni-database-sync
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/endpoints/patroni-database-sync?force=true&fieldManager=database'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/src/charm.py", line 1467, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on endpoints "patroni-database-sync": the object has been modified; please apply your changes to the latest version and try again
unit-database-2: 01:45:02 ERROR unit.database/2.juju-log failed to patch k8s Service patroni-database-config
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 300, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://10.152.183.1/api/v1/namespaces/testing/services/patroni-database-config?force=true&fieldManager=database'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-database-2/charm/src/charm.py", line 1467, in _on_stop
    client.apply(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/client.py", line 493, in patch
    return self._client.request(
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 384, in request
    return self.handle_response(method, resp, br)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 316, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-database-2/charm/venv/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 302, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Operation cannot be fulfilled on services "patroni-database-config": the object has been modified; please apply your changes to the latest version and try again
unit-database-0: 01:46:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 01:46:27 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 01:46:30 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-application-0: 01:46:33 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-1: 01:46:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-0: 01:46:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:46:34 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 01:50:08 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 01:50:11 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-2: 01:51:43 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:51:44 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-1: 01:51:48 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-postgresql-test-app-0: 01:51:48 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-application-0: 01:51:51 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-1: 01:51:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-0: 01:52:15 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:54:39 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-2: 01:54:40 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 01:55:21 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 01:55:23 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-1: 01:57:00 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-application-0: 01:57:03 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-2: 01:58:10 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-1: 01:58:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-0: 02:00:07 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-another-database-2: 02:00:07 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-data-integrator-0: 02:00:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-database-0: 02:01:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...